### ISSUE TITLE
Problem obtaining dependencies to com.sun.media:jai-codec:jar:1.1.3, javax.media:jai-core:jar:1.1.3

### ISSUE THREAD

**Issue by krasinski** [gpc/grails-burning-image#1]
Hello, I'm trying to use this plugin (0.5.2) with Grails 2.4.3 and I'm getting this error:
Error |
Resolve error obtaining dependencies: The following artifacts could not be resolved: com.sun.media:jai-codec:jar:1.1.3, javax.media:jai-core:jar:1.1.3: Could not find artifact com.sun.media:jai-codec:jar:1.1.3 in grailsCentral (http://repo.grails.org/grails/plugins) (Use --stacktrace to see the full trace)

When trying to install older version (0.5.1) there is no error, but older version probably isn't compatible with newer versions of Grails.

**Comment by krasinski** [comment]
Fixed by adding
mavenRepo "https://repository.jboss.org/maven2/" to my BuildConfig
Inspired by ca4c9f331d836d48e65f5e0f94383f622e00be77

**Comment by magraopmw** [comment]
Thanks! Saved my life! :+1: :grinning:

**Comment by liuyouying** [comment]
Thanks!!  it works for me!
